# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(262, 222)
        MainWindow.setMinimumSize(QtCore.QSize(262, 222))
        MainWindow.setMaximumSize(QtCore.QSize(262, 222))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boxEspeciais = QtWidgets.QCheckBox(self.centralwidget)
        self.boxEspeciais.setGeometry(QtCore.QRect(10, 80, 70, 17))
        self.boxEspeciais.setObjectName("boxEspeciais")
        self.boxMaiuscula = QtWidgets.QCheckBox(self.centralwidget)
        self.boxMaiuscula.setGeometry(QtCore.QRect(10, 34, 70, 17))
        self.boxMaiuscula.setObjectName("boxMaiuscula")
        self.boxNumeros = QtWidgets.QCheckBox(self.centralwidget)
        self.boxNumeros.setGeometry(QtCore.QRect(10, 57, 70, 17))
        self.boxNumeros.setObjectName("boxNumeros")
        self.boxMinusculo = QtWidgets.QCheckBox(self.centralwidget)
        self.boxMinusculo.setGeometry(QtCore.QRect(10, 11, 70, 17))
        self.boxMinusculo.setObjectName("boxMinusculo")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 160, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(31)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.boxQntd = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.boxQntd.setMinimum(8)
        self.boxQntd.setObjectName("boxQntd")
        self.horizontalLayout.addWidget(self.boxQntd)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 130, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputRetorno = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.inputRetorno.setObjectName("inputRetorno")
        self.verticalLayout.addWidget(self.inputRetorno)
        self.btnGerar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnGerar.sizePolicy().hasHeightForWidth())
        self.btnGerar.setSizePolicy(sizePolicy)
        self.btnGerar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnGerar.setObjectName("btnGerar")
        self.verticalLayout.addWidget(self.btnGerar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Password Generator"))
        self.boxEspeciais.setText(_translate("MainWindow", "@#$"))
        self.boxMaiuscula.setText(_translate("MainWindow", "A-Z"))
        self.boxNumeros.setText(_translate("MainWindow", "0-9"))
        self.boxMinusculo.setText(_translate("MainWindow", "a-z"))
        self.label.setText(_translate("MainWindow", "Qntd. Caracteres"))
        self.btnGerar.setText(_translate("MainWindow", "Gerar Senha"))
