# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sucesso.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sucesso(object):
    def setupUi(self, Sucesso):
        Sucesso.setObjectName("Sucesso")
        Sucesso.resize(186, 63)
        self.label = QtWidgets.QLabel(Sucesso)
        self.label.setGeometry(QtCore.QRect(43, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnSucesso = QtWidgets.QPushButton(Sucesso)
        self.btnSucesso.setGeometry(QtCore.QRect(63, 35, 60, 23))
        self.btnSucesso.setObjectName("btnSucesso")

        self.retranslateUi(Sucesso)
        QtCore.QMetaObject.connectSlotsByName(Sucesso)

    def retranslateUi(self, Sucesso):
        _translate = QtCore.QCoreApplication.translate
        Sucesso.setWindowTitle(_translate("Sucesso", "Sucesso"))
        self.label.setText(_translate("Sucesso", "Tabela Criada"))
        self.btnSucesso.setText(_translate("Sucesso", "OK"))
