# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'criar_tabela.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(238, 297)
        self.inputNameTable = QtWidgets.QLineEdit(Dialog)
        self.inputNameTable.setGeometry(QtCore.QRect(90, 10, 131, 20))
        self.inputNameTable.setObjectName("inputNameTable")
        self.btnCreate = QtWidgets.QPushButton(Dialog)
        self.btnCreate.setGeometry(QtCore.QRect(80, 260, 75, 23))
        self.btnCreate.setObjectName("btnCreate")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 71, 20))
        self.label_2.setObjectName("label_2")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(60, 50, 171, 151))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 169, 149))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.inputNameColumn = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.inputNameColumn.setObjectName("inputNameColumn")
        self.gridLayout.addWidget(self.inputNameColumn, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 81, 16))
        self.label_3.setObjectName("label_3")
        self.inputPrimaryKey = QtWidgets.QLineEdit(Dialog)
        self.inputPrimaryKey.setGeometry(QtCore.QRect(90, 230, 51, 20))
        self.inputPrimaryKey.setObjectName("inputPrimaryKey")
        self.boxAI = QtWidgets.QCheckBox(Dialog)
        self.boxAI.setGeometry(QtCore.QRect(150, 230, 41, 17))
        self.boxAI.setObjectName("boxAI")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnCreate.setText(_translate("Dialog", "Criar"))
        self.label.setText(_translate("Dialog", "Nome da tabela:"))
        self.label_2.setText(_translate("Dialog", "Colunas:"))
        self.label_3.setText(_translate("Dialog", "Chave Primária:"))
        self.boxAI.setText(_translate("Dialog", "AI"))
